---
# Non-sensitive variables that reference vault variables
porkbun_cert_directory: "/etc/nginx/ssl"
porkbun_reload_nginx: true

# List of domains to manage certificates for
porkbun_domains:
  - collinmurd.foo
  - collinandalivia.com

# Reference encrypted vault variables
porkbun_api_key: "{{ vault_porkbun_api_key }}"
porkbun_secret_key: "{{ vault_porkbun_secret_key }}"
