server {
        listen 443 ssl;
        listen [::]:443 ssl;
        server_name collinandalivia.com www.collinandalivia.com;

        ssl_certificate /etc/nginx/ssl/collinandalivia.com.cert.pem;
        ssl_certificate_key /etc/nginx/ssl/collinandalivia.com.key.pem;

        access_log /var/log/nginx/collinandalivia-access.log;
        error_log /var/log/nginx/collinandalivia-error.log info;

        location / {
                proxy_set_header X-Forwarded-Host $host;
                proxy_pass http://localhost:3002/;
        }
}

server {
        listen 443 ssl;
        listen [::]:443 ssl;
        server_name staging.collinandalivia.com;

        ssl_certificate /etc/nginx/ssl/collinandalivia.com.cert.pem;
        ssl_certificate_key /etc/nginx/ssl/collinandalivia.com.key.pem;

        access_log /var/log/nginx/collinandalivia-staging-access.log;
        error_log /var/log/nginx/collinandalivia-staging-error.log info;

        location / {
                proxy_pass http://localhost:3003/;
        }
}
