---
- name: Remove default nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: reload nginx

# Configure nginx for collinmurd.foo
- name: Copy site configuration for collinmurd.foo
  copy:
    src: etc/nginx/collinmurd.foo.nginx.conf
    dest: /etc/nginx/sites-available/collinmurd.foo
    owner: root
    group: root
    mode: "0644"
  notify: reload nginx

- name: Enable site configuration for collinmurd.foo
  file:
    src: /etc/nginx/sites-available/collinmurd.foo
    dest: /etc/nginx/sites-enabled/collinmurd.foo
    state: link
  notify: reload nginx

# Configure nginx for collinandalivia.com
- name: Copy site configuration for collinandalivia.com
  copy:
    src: etc/nginx/collinandalivia.com.nginx.conf
    dest: /etc/nginx/sites-available/collinandalivia.com
    owner: root
    group: root
    mode: "0644"
  notify: reload nginx

- name: Enable site configuration for collinandalivia.com
  file:
    src: /etc/nginx/sites-available/collinandalivia.com
    dest: /etc/nginx/sites-enabled/collinandalivia.com
    state: link
  notify: reload nginx

# Configure nginx for the default 421 site
- name: Copy site configuration for the default 421 site
  copy:
    src: etc/nginx/default.nginx.conf
    dest: /etc/nginx/sites-available/default
    owner: root
    group: root
    mode: "0644"
  notify: reload nginx

- name: Enable site configuration for the default 421 site
  file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link
  notify: reload nginx

- name: Ensure nginx is running and enabled
  systemd:
    name: nginx
    state: started
    enabled: yes
