# Local resources for generating dynamic configuration files

# Generate Ansible inventory file from Terraform state
resource "local_file" "ansible_inventory" {
  content = <<-EOT
# This file is auto-generated by Terraform
# Last updated: ${timestamp()}

[groceries_servers]
${oci_core_instance.main.display_name} ansible_host=${oci_core_instance.main.public_ip} ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa

[groceries_servers:vars]
ansible_python_interpreter=/usr/bin/python3
EOT

  filename        = "${path.module}/../ansible/inventory.ini"
  file_permission = "0644"
}
